package:
  name: pyqtgraph
  version: 0.9.10
  # use the following once https://github.com/conda/conda-build/issues/764 gets fixed:
  # {{ environ.get("GIT_DESCRIBE_TAG", "")[10:] }}

source:
  git_url: ../..
  git_rev: develop

build:
  number: {{ environ.get("GIT_DESCRIBE_NUMBER", 0) }}
  string: py_{{ environ.get("GIT_DESCRIBE_NUMBER", 0) }}+git{{ environ.get("GIT_DESCRIBE_HASH", "")[1:] }}
  noarch_python: true
  script: $PYTHON setup.py install

requirements:
  build:
    - python
    - setuptools
    - numpy

  run:
    - python
    - numpy
    - pyqt

test:
  imports:
    - pyqtgraph

about:
  home: http://www.pyqtgraph.org
  license: MIT License
  summary: 'Scientific Graphics and GUI Library for Python'
